### 회원 생성
POST localhost:8000/api/users
Content-Type: application/json

{
  "userName" : "Seoyun",
  "address" : "Daejeon-si, Daedeok-gu, Songchon-dong",
  "phoneNumber" : "010-0000-0000",
  "email" : "Seoyun@wisoft.io"
}

### 회원 전체 조회
GET localhost:8000/api/users
Accept: application/json

### 회원 수정
PATCH localhost:8000/api/users/64119f389e9393f2d3d40828
Content-Type: application/json

{
  "userName" : "juno"
}

### 회원 삭제
DELETE localhost:8000/api/users/64119fe19e9393f2d3d40829
Accept: application/json

### 회원 검색 (이름)
GET localhost:8000/api/users?userName=juno
Accept: application/json

### 회원 검색 (주소)
GET localhost:8000/api/users?address=Daedeok-gu
Accept: application/json